version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
before_deploy:
- ps: dotnet pack AutoMockHelper.Core
deploy:
- provider: NuGet
  api_key:
    secure: RTLuX5RDfgWBz1BsMyyH+sVRVf/3Uj/VwNEWbSq8xMZYvwJX/U57k8s8YnMtTQkr
  skip_symbols: false
  artifact: /.*\.nupkg/